//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpBotAdmin.Storage
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Students
    {
        [Display(Name = "Идентификатор", Description = "Идентификатор пользователя в Telegram")]
        public int UserID { get; set; }

        [Display(Name = "Учетная запись")]
        public string UserName { get; set; }

        [Display(Name = "Имя")]
        public string Name { get; set; }

        [Display(Name = "Фамилия")]
        public string FamilyName { get; set; }

        [Display(Name = "Электронная почта")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Требуется ввести адрес электронной почты")]
        [EmailAddress(ErrorMessage = "Требуется ввести корректный адрес электронной почты")]
        public string EMail { get; set; }

        public System.Guid ID { get; set; }

        [Display(Name = "Телефон")]
        public string PhoneNumber { get; set; }
    }
}
