// <auto-generated />
namespace CROC.Education.CSharpBotService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Student3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Student3));
        
        string IMigrationMetadata.Id
        {
            get { return "201711011845593_Student3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
